logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

clients:
  base-url: http://localhost:8090/clientes/