logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/clients
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

